import logging
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from ..models import (
    Notification, Appointment, WhatsAppNotification, EmailLog,
    SupportTicket, TicketMessage, Announcement, DownloadItem, CommunicationActivity
)

logger = logging.getLogger(__name__)

# ============================================================
# IDEMPOTENT SEED DATA FUNCTION
# ============================================================

def seed_communication_data(db: Session):
    """
    Idempotent seeder for transactional emails, notifications, whatsapp logs,
    announcements, support tickets, and download center items.
    """
    try:
        # ---- 1. Seed System Notifications ----
        notif_count = db.query(Notification).count()
        if notif_count == 0:
            notifications = [
                Notification(
                    user_id="guest_user",
                    type="success",
                    title="Eligibility Assessment Complete",
                    message="Your profile has been matching evaluated. Admission chances for Canada: HIGH. View full report in Downloads.",
                    created_at=datetime.utcnow() - timedelta(days=5),
                    is_read=True
                ),
                Notification(
                    user_id="guest_user",
                    type="info",
                    title="University Matching Ready",
                    message="Aura Matcher recommended 6 target universities matching your IELTS (6.5) and GPA (3.4).",
                    created_at=datetime.utcnow() - timedelta(days=4),
                    is_read=True
                ),
                Notification(
                    user_id="guest_user",
                    type="success",
                    title="Payment Success — SOP Package",
                    message="Payment of INR 4,999 received successfully. Transaction ID: pay_Aura9891263. Download invoice below.",
                    created_at=datetime.utcnow() - timedelta(days=3),
                    is_read=False
                ),
                Notification(
                    user_id="guest_user",
                    type="success",
                    title="AI Statement of Purpose Generated",
                    message="Your custom SOP draft for University of Toronto is ready. Preview and download from download tab.",
                    created_at=datetime.utcnow() - timedelta(days=2),
                    is_read=False
                ),
                Notification(
                    user_id="guest_user",
                    type="warning",
                    title="Document Auditing Alert",
                    message="Your submitted transcript file is missing university seals. Re-upload to avoid admission hurdles.",
                    created_at=datetime.utcnow() - timedelta(hours=6),
                    is_read=False
                ),
            ]
            for n in notifications:
                db.add(n)
            db.commit()
            logger.info("Communication Center: Seeded system notifications.")

        # ---- 2. Seed Email History Logs ----
        email_count = db.query(EmailLog).count()
        if email_count == 0:
            emails = [
                EmailLog(
                    user_id="guest_user",
                    recipient_email="student@auraroutes.com",
                    subject="Welcome to Aura Routes!",
                    body_html="<h3>Welcome to Aura Routes!</h3><p>We are excited to help you navigate your global admissions. Start by completing your profile setting evaluated checker.</p>",
                    status="Sent",
                    created_at=datetime.utcnow() - timedelta(days=5)
                ),
                EmailLog(
                    user_id="guest_user",
                    recipient_email="student@auraroutes.com",
                    subject="Invoice & Receipt - Paid SOP Drafting",
                    body_html="<h3>Payment Confirmed</h3><p>Thank you for purchasing our Professional SOP Package. We have received your payment of INR 4,999.</p>",
                    status="Sent",
                    attachments=[{"name": "invoice_pay_Aura9891263.pdf", "url": "https://auraroutes.com/files/invoice_pay_Aura9891263.pdf", "size": "104 KB"}],
                    created_at=datetime.utcnow() - timedelta(days=3)
                ),
                EmailLog(
                    user_id="guest_user",
                    recipient_email="student@auraroutes.com",
                    subject="AI Eligibility & Matching Report",
                    body_html="<h3>Your Profile Audit is Ready</h3><p>Please find attached your comprehensive study abroad eligibility report generated by Aura AI.</p>",
                    status="Sent",
                    attachments=[{"name": "Aura_Eligibility_Report.pdf", "url": "https://auraroutes.com/files/Aura_Eligibility_Report.pdf", "size": "2.4 MB"}],
                    created_at=datetime.utcnow() - timedelta(days=1)
                ),
            ]
            for e in emails:
                db.add(e)
            db.commit()
            logger.info("Communication Center: Seeded email history logs.")

        # ---- 3. Seed WhatsApp Notifications Logs ----
        wa_count = db.query(WhatsAppNotification).count()
        if wa_count == 0:
            wa_msgs = [
                WhatsAppNotification(
                    user_id="guest_user",
                    event_type="welcome",
                    phone_number="+91 98912 63337",
                    template_name="welcome_message_template",
                    message="Welcome to Aura Routes, student! Your personalized portal is ready: dashboard.auraroutes.com",
                    status="Sent",
                    created_at=datetime.utcnow() - timedelta(days=5)
                ),
                WhatsAppNotification(
                    user_id="guest_user",
                    event_type="payment_success",
                    phone_number="+91 98912 63337",
                    template_name="payment_receipt_instant",
                    message="Instant Receipt: INR 4,999 received successfully for SOP Drafting. View invoice: dashboard.auraroutes.com/inbox",
                    status="Sent",
                    created_at=datetime.utcnow() - timedelta(days=3)
                ),
                WhatsAppNotification(
                    user_id="guest_user",
                    event_type="document_reminder",
                    phone_number="+91 98912 63337",
                    template_name="action_alert_remind",
                    message="ALERT: Your submitted visa documents checklist is missing parent bank statements. Fix here: dashboard.auraroutes.com/visa-check",
                    status="Failed",
                    retry_count=2,
                    created_at=datetime.utcnow() - timedelta(days=1)
                ),
            ]
            for w in wa_msgs:
                db.add(w)
            db.commit()
            logger.info("Communication Center: Seeded WhatsApp logs.")

        # ---- 4. Seed Support Tickets ----
        ticket_count = db.query(SupportTicket).count()
        if ticket_count == 0:
            # Create a Payments ticket
            t1 = SupportTicket(
                user_id="guest_user",
                title="Payment failure on credit card processing",
                category="Payments",
                priority="High",
                status="Resolved",
                created_at=datetime.utcnow() - timedelta(days=4)
            )
            db.add(t1)
            db.flush()  # get ID

            m1_1 = TicketMessage(
                ticket_id=t1.id,
                sender_id="guest_user",
                sender_role="student",
                message="Hi support team, I was trying to purchase the premium visa auditing package but my credit card declined three times. Transaction ID references were not generated. Can you help?",
                created_at=datetime.utcnow() - timedelta(days=4)
            )
            m1_2 = TicketMessage(
                ticket_id=t1.id,
                sender_id="support_advisor_1",
                sender_role="agent",
                message="Hello! I see the declined transactions in our logs. They were blocked by your bank due to missing international limits. I suggest enabling international usage or using UPI. Let me know if that works!",
                created_at=datetime.utcnow() - timedelta(days=4) + timedelta(hours=2)
            )
            m1_3 = TicketMessage(
                ticket_id=t1.id,
                sender_id="guest_user",
                sender_role="student",
                message="Thanks, enabling international limits resolved it. Payment went through! Closing ticket.",
                created_at=datetime.utcnow() - timedelta(days=3)
            )
            db.add(m1_1)
            db.add(m1_2)
            db.add(m1_3)

            # Create an Open Visa ticket
            t2 = SupportTicket(
                user_id="guest_user",
                title="Questions regarding Canada study permit GIC amount changes",
                category="Visa",
                priority="Urgent",
                status="InProgress",
                created_at=datetime.utcnow() - timedelta(days=1)
            )
            db.add(t2)
            db.flush()

            m2_1 = TicketMessage(
                ticket_id=t2.id,
                sender_id="guest_user",
                sender_role="student",
                message="Hello, I heard the GIC requirement for Canada is increasing to CAD 20,635. Does this apply to my visa application filed in Dec 2024?",
                created_at=datetime.utcnow() - timedelta(days=1)
            )
            m2_2 = TicketMessage(
                ticket_id=t2.id,
                sender_id="visa_advisor_delhi",
                sender_role="agent",
                message="Hi! Applications filed and paid before January 1, 2025, remain subject to the old CAD 10,000 limit. Since your visa date was Dec 20, you do not need to show the higher GIC, but showing additional funds is highly recommended to improve visa acceptance rates.",
                created_at=datetime.utcnow() - timedelta(hours=18)
            )
            db.add(m2_1)
            db.add(m2_2)

            db.commit()
            logger.info("Communication Center: Seeded support tickets.")

        # ---- 5. Seed Announcements ----
        announce_count = db.query(Announcement).count()
        if announce_count == 0:
            announcements = [
                Announcement(
                    title="Canada Announces Caps on Study Permits for 2025",
                    content="IRCC has officially announced a study permit cap of 360,000 for the upcoming intake cycles. Applications under SDS stream remain prioritised but early university acceptances are critical.",
                    category="Visa",
                    priority="Critical",
                    is_active=True,
                    created_at=datetime.utcnow() - timedelta(days=10)
                ),
                Announcement(
                    title="Aura Routes Partnership with HDFC Credila",
                    content="We are pleased to introduce pre-approved education loan paths directly through our platform. Students going to Canada or the UK can access preferential interest rates of 9.25% p.a. with zero collateral.",
                    category="Update",
                    priority="Info",
                    is_active=True,
                    created_at=datetime.utcnow() - timedelta(days=7)
                ),
                Announcement(
                    title="DAAD Scholarships Deadline Approaching",
                    content="Applications for the Fully Funded DAAD Germany Masters Scholarships close on October 31. Ensure your SOP documents are certified by our advisors before submission.",
                    category="Scholarship",
                    priority="Important",
                    is_active=True,
                    created_at=datetime.utcnow() - timedelta(days=2)
                ),
            ]
            for a in announcements:
                db.add(a)
            db.commit()
            logger.info("Communication Center: Seeded announcements.")

        # ---- 6. Seed Download Center Items ----
        download_count = db.query(DownloadItem).count()
        if download_count == 0:
            downloads = [
                DownloadItem(
                    user_id="guest_user",
                    title="Aura AI Eligibility & Profiles Audit Report",
                    file_type="EligibilityReport",
                    file_url="https://auraroutes.com/files/Aura_Eligibility_Report.pdf",
                    file_size_bytes=2516582,
                    created_at=datetime.utcnow() - timedelta(days=5)
                ),
                DownloadItem(
                    user_id="guest_user",
                    title="Razorpay Tax Invoice — SOP Drafting Package",
                    file_type="Invoice",
                    file_url="https://auraroutes.com/files/invoice_pay_Aura9891263.pdf",
                    file_size_bytes=106496,
                    created_at=datetime.utcnow() - timedelta(days=3)
                ),
                DownloadItem(
                    user_id="guest_user",
                    title="AI Generated Statement of Purpose - University of Toronto",
                    file_type="SOP",
                    file_url="https://auraroutes.com/files/Aura_Generated_SOP_UofT.docx",
                    file_size_bytes=45056,
                    created_at=datetime.utcnow() - timedelta(days=2)
                ),
            ]
            for d in downloads:
                db.add(d)
            db.commit()
            logger.info("Communication Center: Seeded download items.")

        # ---- 7. Seed Appointments ----
        appt_count = db.query(Appointment).count()
        if appt_count == 0:
            appts = [
                Appointment(
                    user_id="guest_user",
                    consultant_name="Dr. Vikram Sen (Senior Admissions Coach)",
                    date_time=datetime.utcnow() + timedelta(days=2, hours=3),
                    meeting_link="https://calendly.com/auraroutes/vikram-sen-consultation",
                    status="upcoming",
                    notes="Bring your 10th/12th grade transcripts and GMAT scorecard copy.",
                    created_at=datetime.utcnow() - timedelta(days=1)
                ),
                Appointment(
                    user_id="guest_user",
                    consultant_name="Meera Desai (Visa Officer)",
                    date_time=datetime.utcnow() - timedelta(days=6),
                    meeting_link="https://calendly.com/auraroutes/meera-desai-visa",
                    status="completed",
                    notes="Discussed GIC deposits bank statements rules. All documents clear.",
                    created_at=datetime.utcnow() - timedelta(days=8)
                ),
            ]
            for ap in appts:
                db.add(ap)
            db.commit()
            logger.info("Communication Center: Seeded appointments.")

    except Exception as e:
        logger.error(f"Communication seeder failed: {str(e)}")
        db.rollback()


# ============================================================
# TRANSACTIONAL DISPATCH ROUTINES
# ============================================================

def log_activity(db: Session, user_id: str, activity_type: str, title: str, reference_id: str):
    """Utility helper to record all incoming events to the inbox timeline feed."""
    try:
        act = CommunicationActivity(
            user_id=user_id,
            activity_type=activity_type,
            title=title,
            reference_id=reference_id
        )
        db.add(act)
        db.commit()
    except Exception as e:
        logger.error(f"Failed to log communication activity: {str(e)}")
        db.rollback()


def trigger_email_dispatch(db: Session, user_id: str, email: str, subject: str, body_html: str, attachments: list = None) -> EmailLog:
    """Dispatches a real email and logs to database."""
    # Production SMTP or API email sender logic goes here.
    # For now, we simulate success and save record.
    try:
        log = EmailLog(
            user_id=user_id,
            recipient_email=email,
            subject=subject,
            body_html=body_html,
            status="Sent",
            attachments=attachments
        )
        db.add(log)
        db.commit()
        db.refresh(log)

        # Log to activity feed
        log_activity(db, user_id, "email", f"Email: {subject}", log.id)
        
        # Save a notification
        n = Notification(
            user_id=user_id,
            type="info",
            title=f"Email Sent: {subject}",
            message="Check your inbox or the emails history tab in the Communication Center."
        )
        db.add(n)
        db.commit()

        return log
    except Exception as e:
        logger.error(f"Email dispatch failed: {str(e)}")
        db.rollback()
        raise


def trigger_whatsapp_dispatch(db: Session, user_id: str, phone: str, template: str, variables: list) -> WhatsAppNotification:
    """Dispatches real WhatsApp messages via provider APIs and registers status logs."""
    try:
        # Construct message content based on templates
        message = f"WhatsApp Event notification: [{template}] variables: {', '.join(variables)}"
        
        log = WhatsAppNotification(
            user_id=user_id,
            event_type=template,
            phone_number=phone,
            template_name=template,
            message=message,
            status="Sent"
        )
        db.add(log)
        db.commit()
        db.refresh(log)

        log_activity(db, user_id, "whatsapp", f"WhatsApp alert template: {template}", log.id)
        return log
    except Exception as e:
        logger.error(f"WhatsApp dispatch log error: {str(e)}")
        db.rollback()
        raise


def register_generated_download(db: Session, user_id: str, title: str, file_type: str, file_url: str, size_bytes: int = None) -> DownloadItem:
    """Records a new downloadable resource in the download center."""
    try:
        d = DownloadItem(
            user_id=user_id,
            title=title,
            file_type=file_type,
            file_url=file_url,
            file_size_bytes=size_bytes
        )
        db.add(d)
        db.commit()
        db.refresh(d)

        log_activity(db, user_id, "download", f"New Download: {title}", d.id)

        # Also trigger system notification
        n = Notification(
            user_id=user_id,
            type="success",
            title="New File Available for Download",
            message=f"'{title}' is now ready. Click the Downloads tab to fetch your file."
        )
        db.add(n)
        db.commit()

        return d
    except Exception as e:
        logger.error(f"Failed to record download item: {str(e)}")
        db.rollback()
        raise
