import logging
from sqlalchemy.orm import Session
from ..models import ExplorerUniversity, ExplorerCourse, ExplorerCountry
from ..config import settings

logger = logging.getLogger(__name__)


# ============================================================
# COUNTRIES SEED DATA
# ============================================================
COUNTRIES_SEED = [
    {
        "slug": "canada",
        "name": "Canada",
        "flag_emoji": "🇨🇦",
        "description": "Canada is one of the world's top study destinations, renowned for its world-class universities, multicultural environment, high quality of life, and excellent post-study work pathways. International students benefit from affordable tuition compared to the USA, two-year post-graduation work permits, and a clear pathway to permanent residency.",
        "living_cost_monthly_display": "CAD 1,500 - 2,500/month",
        "living_cost_monthly_usd": 1100.0,
        "avg_rent_display": "CAD 700 - 1,400/month",
        "avg_food_display": "CAD 400 - 700/month",
        "avg_transport_display": "CAD 100 - 150/month",
        "student_visa_name": "Study Permit",
        "visa_processing_time": "4–8 weeks",
        "visa_fee_display": "CAD 150",
        "visa_requirements_summary": ["Valid passport", "Letter of Acceptance", "Proof of funds (CAD 10,000+)", "Biometrics fee", "Medical exam (if required)"],
        "visa_difficulty": "Easy",
        "work_rights_during_study": "20 hours/week during semester, full-time during breaks",
        "work_hours_per_week": 20,
        "post_study_work_visa": "Post-Graduation Work Permit (PGWP)",
        "post_study_work_duration": "Up to 3 years",
        "average_salary_display": "CAD 55,000 - 90,000/year",
        "top_industries": ["Technology", "Healthcare", "Engineering", "Finance", "Education"],
        "popular_courses": ["Computer Science", "Business Administration", "Engineering", "Medicine", "Data Science"],
        "climate": "Temperate to subarctic; warm summers, cold winters. Varies significantly by province.",
        "official_language": "English & French",
        "currency": "Canadian Dollar (CAD)",
        "government_scholarships": [
            {"name": "Vanier Canada Graduate Scholarships", "amount": "CAD 50,000/year", "description": "For doctoral students demonstrating leadership and research excellence"},
            {"name": "Banting Postdoctoral Fellowships", "amount": "CAD 70,000/year", "description": "For postdoctoral research in Canada"},
            {"name": "Ontario Graduate Scholarship", "amount": "CAD 10,000/year", "description": "For graduate students in Ontario universities"}
        ],
        "ai_summary": "Canada offers one of the most accessible study abroad pathways for Indian students. With affordable tuition, world-class universities, and a direct route to permanent residency via Express Entry, it consistently ranks as the #1 destination for Indian students.",
        "total_universities": 100,
        "is_featured": True
    },
    {
        "slug": "uk",
        "name": "United Kingdom",
        "flag_emoji": "🇬🇧",
        "description": "The UK is home to some of the world's oldest and most prestigious universities including Oxford and Cambridge. With a shorter program duration compared to other countries, students can complete a Master's in just one year. The Graduate Route visa allows 2 years of post-study work.",
        "living_cost_monthly_display": "GBP 1,200 - 1,800/month",
        "living_cost_monthly_usd": 1500.0,
        "avg_rent_display": "GBP 600 - 1,200/month",
        "avg_food_display": "GBP 200 - 400/month",
        "avg_transport_display": "GBP 80 - 150/month",
        "student_visa_name": "Student Visa (Tier 4)",
        "visa_processing_time": "3–6 weeks",
        "visa_fee_display": "GBP 363",
        "visa_requirements_summary": ["CAS (Confirmation of Acceptance for Studies)", "Valid passport", "Proof of funds", "English language test", "ATAS certificate (for certain courses)"],
        "visa_difficulty": "Medium",
        "work_rights_during_study": "20 hours/week during term, full-time during holidays",
        "work_hours_per_week": 20,
        "post_study_work_visa": "Graduate Route Visa",
        "post_study_work_duration": "2 years (3 years for PhD)",
        "average_salary_display": "GBP 30,000 - 55,000/year",
        "top_industries": ["Finance", "Technology", "Healthcare", "Creative Industries", "Research"],
        "popular_courses": ["Business & Management", "Computer Science", "Law", "Medicine", "Engineering"],
        "climate": "Temperate maritime; mild, wet, and overcast throughout the year.",
        "official_language": "English",
        "currency": "British Pound (GBP)",
        "government_scholarships": [
            {"name": "Chevening Scholarships", "amount": "Full scholarship", "description": "UK government's global scholarship programme"},
            {"name": "Commonwealth Scholarship", "amount": "Full scholarship", "description": "For students from Commonwealth countries"},
            {"name": "GREAT Scholarships", "amount": "GBP 10,000+", "description": "For Indian students pursuing postgraduate degrees"}
        ],
        "ai_summary": "The UK's 1-year Master's programs are extremely cost-efficient for Indian students when factoring in duration. The Graduate Route visa provides 2 years to gain UK work experience, making it a strong launchpad for international careers.",
        "total_universities": 160,
        "is_featured": True
    },
    {
        "slug": "australia",
        "name": "Australia",
        "flag_emoji": "🇦🇺",
        "description": "Australia combines academic excellence with an outstanding quality of life. Home to 7 of the world's top 100 universities, Australia offers excellent research facilities, a safe multicultural environment, and generous post-study work rights of up to 4 years.",
        "living_cost_monthly_display": "AUD 1,800 - 2,800/month",
        "living_cost_monthly_usd": 1200.0,
        "avg_rent_display": "AUD 800 - 1,500/month",
        "avg_food_display": "AUD 400 - 700/month",
        "avg_transport_display": "AUD 150 - 250/month",
        "student_visa_name": "Student Visa (Subclass 500)",
        "visa_processing_time": "4–6 weeks",
        "visa_fee_display": "AUD 710",
        "visa_requirements_summary": ["Confirmation of Enrolment (CoE)", "Genuine Temporary Entrant (GTE) statement", "English proficiency", "Financial evidence", "Health insurance (OSHC)"],
        "visa_difficulty": "Easy",
        "work_rights_during_study": "Unlimited hours per week (no cap since 2023)",
        "work_hours_per_week": 48,
        "post_study_work_visa": "Temporary Graduate Visa (Subclass 485)",
        "post_study_work_duration": "2–4 years depending on qualification level",
        "average_salary_display": "AUD 60,000 - 100,000/year",
        "top_industries": ["Mining & Resources", "Healthcare", "Technology", "Agriculture", "Tourism"],
        "popular_courses": ["Engineering", "Nursing", "Computer Science", "Business", "Agriculture"],
        "climate": "Varies from tropical in the north to temperate in the south. Generally sunny and warm.",
        "official_language": "English",
        "currency": "Australian Dollar (AUD)",
        "government_scholarships": [
            {"name": "Australia Awards Scholarships", "amount": "Full scholarship", "description": "For students from developing countries"},
            {"name": "Destination Australia Scholarships", "amount": "AUD 15,000/year", "description": "For regional study in Australia"},
            {"name": "Research Training Program", "amount": "Fee offset + stipend", "description": "For PhD and Master's by research students"}
        ],
        "ai_summary": "Australia's unlimited work rights during study and generous post-study work visas make it ideal for students who want to combine academics with practical work experience. The pathway to PR is also strong via skilled migration streams.",
        "total_universities": 43,
        "is_featured": True
    },
    {
        "slug": "usa",
        "name": "United States",
        "flag_emoji": "🇺🇸",
        "description": "The USA hosts more top-ranked universities than any other country in the world. American universities are known for cutting-edge research, innovation, strong alumni networks, and diverse campus life. The OPT program allows 1-3 years of work experience after graduation.",
        "living_cost_monthly_display": "USD 1,500 - 3,000/month",
        "living_cost_monthly_usd": 1800.0,
        "avg_rent_display": "USD 800 - 1,800/month",
        "avg_food_display": "USD 400 - 700/month",
        "avg_transport_display": "USD 100 - 200/month",
        "student_visa_name": "F-1 Student Visa",
        "visa_processing_time": "3–8 weeks",
        "visa_fee_display": "USD 185 + SEVIS fee USD 350",
        "visa_requirements_summary": ["I-20 form from university", "DS-160 application", "Visa interview at embassy", "Financial proof", "SEVIS registration"],
        "visa_difficulty": "Hard",
        "work_rights_during_study": "20 hours/week on-campus only",
        "work_hours_per_week": 20,
        "post_study_work_visa": "OPT (Optional Practical Training)",
        "post_study_work_duration": "1 year (3 years for STEM graduates)",
        "average_salary_display": "USD 55,000 - 110,000/year",
        "top_industries": ["Technology", "Finance", "Healthcare", "Consulting", "Research"],
        "popular_courses": ["Computer Science", "MBA", "Electrical Engineering", "Data Science", "Medicine"],
        "climate": "Highly varied by region — tropical in Florida, arid in the Southwest, continental in the Midwest.",
        "official_language": "English",
        "currency": "US Dollar (USD)",
        "government_scholarships": [
            {"name": "Fulbright Foreign Student Program", "amount": "Full scholarship", "description": "Prestigious U.S. government exchange scholarship"},
            {"name": "Humphrey Fellowship Program", "amount": "Full funding", "description": "For experienced professionals"},
        ],
        "ai_summary": "The USA offers unmatched research opportunities and alumni networks. STEM students benefit from the 3-year OPT extension and H-1B sponsorship pathway. However, tuition and living costs are highest among all destinations.",
        "total_universities": 4000,
        "is_featured": True
    },
    {
        "slug": "germany",
        "name": "Germany",
        "flag_emoji": "🇩🇪",
        "description": "Germany offers tuition-free education at public universities for both domestic and international students. Renowned for engineering, technology, and research excellence, Germany attracts over 400,000 international students annually. After graduation, students can stay for 18 months to find employment.",
        "living_cost_monthly_display": "EUR 800 - 1,200/month",
        "living_cost_monthly_usd": 950.0,
        "avg_rent_display": "EUR 300 - 600/month",
        "avg_food_display": "EUR 200 - 350/month",
        "avg_transport_display": "EUR 80 - 120/month",
        "student_visa_name": "German Student Visa (National Visa D)",
        "visa_processing_time": "6–12 weeks",
        "visa_fee_display": "EUR 75",
        "visa_requirements_summary": ["University admission letter", "Financial proof (EUR 10,332/year)", "Health insurance", "German language proficiency (for German-taught programs)", "Blocked bank account"],
        "visa_difficulty": "Medium",
        "work_rights_during_study": "120 full days or 240 half days per year",
        "work_hours_per_week": 20,
        "post_study_work_visa": "Job Seeker Visa",
        "post_study_work_duration": "18 months",
        "average_salary_display": "EUR 35,000 - 65,000/year",
        "top_industries": ["Automotive", "Engineering", "Technology", "Chemicals", "Finance"],
        "popular_courses": ["Engineering", "Computer Science", "Natural Sciences", "Business", "Medicine"],
        "climate": "Temperate continental; warm summers, cold winters, moderate rainfall year-round.",
        "official_language": "German (many programs taught in English)",
        "currency": "Euro (EUR)",
        "government_scholarships": [
            {"name": "DAAD Scholarship", "amount": "EUR 861/month + benefits", "description": "Germany's largest scholarship program for international students"},
            {"name": "Deutschlandstipendium", "amount": "EUR 300/month", "description": "National scholarship program co-funded by businesses"},
        ],
        "ai_summary": "Germany is the best value study destination globally. Public universities charge only a semester fee of EUR 150-350 — essentially tuition-free. The strong engineering and tech job market offers excellent career prospects after graduation.",
        "total_universities": 400,
        "is_featured": True
    },
    {
        "slug": "ireland",
        "name": "Ireland",
        "flag_emoji": "🇮🇪",
        "description": "Ireland is an English-speaking EU country with a thriving tech and pharmaceutical industry. Home to European headquarters of Google, Facebook, Apple, and Microsoft, Ireland offers excellent employment prospects for tech graduates. The Stay Back visa allows 2 years post-study work.",
        "living_cost_monthly_display": "EUR 1,200 - 1,800/month",
        "living_cost_monthly_usd": 1300.0,
        "avg_rent_display": "EUR 700 - 1,200/month",
        "avg_food_display": "EUR 250 - 400/month",
        "avg_transport_display": "EUR 100 - 150/month",
        "student_visa_name": "Irish Study Visa (C Study Visa)",
        "visa_processing_time": "4–8 weeks",
        "visa_fee_display": "EUR 60",
        "visa_requirements_summary": ["University offer letter", "Proof of fees paid", "Financial evidence", "English proficiency", "Private health insurance"],
        "visa_difficulty": "Easy",
        "work_rights_during_study": "20 hours/week during term, 40 hours/week during holidays",
        "work_hours_per_week": 20,
        "post_study_work_visa": "Third Level Graduate Scheme",
        "post_study_work_duration": "2 years",
        "average_salary_display": "EUR 35,000 - 65,000/year",
        "top_industries": ["Technology", "Pharmaceuticals", "Finance", "Healthcare", "Tourism"],
        "popular_courses": ["Computer Science", "Data Analytics", "Business", "Pharmacy", "Finance"],
        "climate": "Mild, temperate, and wet. Rarely extremely hot or cold due to Atlantic influence.",
        "official_language": "English & Irish",
        "currency": "Euro (EUR)",
        "government_scholarships": [
            {"name": "Government of Ireland International Education Scholarships", "amount": "EUR 10,000", "description": "For non-EU students studying in Ireland"},
        ],
        "ai_summary": "Ireland is increasingly popular among tech-focused Indian students due to the presence of global tech giants. Being English-speaking and EU-based provides access to Europe's job market while eliminating language barriers.",
        "total_universities": 34,
        "is_featured": True
    },
    {
        "slug": "new-zealand",
        "name": "New Zealand",
        "flag_emoji": "🇳🇿",
        "description": "New Zealand offers a safe, friendly, and stunning natural environment for international students. With world-class universities and a clear PR pathway, New Zealand is a growing study destination. The Post Study Work visa allows up to 3 years of work after graduation.",
        "living_cost_monthly_display": "NZD 1,500 - 2,200/month",
        "living_cost_monthly_usd": 950.0,
        "avg_rent_display": "NZD 700 - 1,200/month",
        "avg_food_display": "NZD 400 - 600/month",
        "avg_transport_display": "NZD 100 - 180/month",
        "student_visa_name": "Student Visa",
        "visa_processing_time": "4–6 weeks",
        "visa_fee_display": "NZD 375",
        "visa_requirements_summary": ["Offer of place from institution", "Evidence of funds", "Health and character requirements", "English language evidence"],
        "visa_difficulty": "Easy",
        "work_rights_during_study": "20 hours/week during term",
        "work_hours_per_week": 20,
        "post_study_work_visa": "Post Study Work Visa",
        "post_study_work_duration": "1–3 years",
        "average_salary_display": "NZD 50,000 - 80,000/year",
        "top_industries": ["Agriculture", "Technology", "Healthcare", "Tourism", "Construction"],
        "popular_courses": ["Agriculture", "Engineering", "Computer Science", "Nursing", "Hospitality"],
        "climate": "Temperate maritime; generally mild year-round with regional variations.",
        "official_language": "English, Māori, NZ Sign Language",
        "currency": "New Zealand Dollar (NZD)",
        "government_scholarships": [
            {"name": "New Zealand Excellence Awards", "amount": "NZD 10,000", "description": "For high-achieving international students"},
        ],
        "ai_summary": "New Zealand is an ideal destination for students seeking quality education in a safe, beautiful environment. The PR pathway is straightforward for skilled workers, particularly in high-demand sectors like healthcare, engineering, and agriculture.",
        "total_universities": 8,
        "is_featured": False
    },
    {
        "slug": "singapore",
        "name": "Singapore",
        "flag_emoji": "🇸🇬",
        "description": "Singapore is Asia's premier study destination, home to world-ranked NUS and NTU. As a global financial and tech hub, Singapore offers exceptional career opportunities. English is the primary language of instruction, making it accessible to Indian students.",
        "living_cost_monthly_display": "SGD 1,500 - 2,500/month",
        "living_cost_monthly_usd": 1100.0,
        "avg_rent_display": "SGD 700 - 1,500/month",
        "avg_food_display": "SGD 300 - 500/month",
        "avg_transport_display": "SGD 100 - 150/month",
        "student_visa_name": "Student's Pass (STP)",
        "visa_processing_time": "4–8 weeks",
        "visa_fee_display": "SGD 90",
        "visa_requirements_summary": ["Acceptance letter from institution", "IPA letter from ICA", "Passport", "Medical exam", "Financial evidence"],
        "visa_difficulty": "Medium",
        "work_rights_during_study": "16 hours/week with authorization",
        "work_hours_per_week": 16,
        "post_study_work_visa": "Work visa (Employment Pass or S Pass)",
        "post_study_work_duration": "Employer-dependent, typically renewable",
        "average_salary_display": "SGD 45,000 - 80,000/year",
        "top_industries": ["Finance", "Technology", "Biomedical", "Logistics", "Tourism"],
        "popular_courses": ["Business", "Computer Science", "Engineering", "Finance", "Biomedical Sciences"],
        "climate": "Tropical; hot and humid year-round with frequent rainfall.",
        "official_language": "English, Mandarin, Malay, Tamil",
        "currency": "Singapore Dollar (SGD)",
        "government_scholarships": [
            {"name": "Singapore Government Scholarship (ASEAN)", "amount": "Full scholarship", "description": "For ASEAN students at NUS/NTU/SMU"},
        ],
        "ai_summary": "Singapore is ideal for students targeting careers in finance, technology, and biomedical research. NUS and NTU consistently rank in the global top 20, and Singapore's strategic location makes it a gateway to the entire Asia-Pacific job market.",
        "total_universities": 6,
        "is_featured": True
    },
    {
        "slug": "netherlands",
        "name": "Netherlands",
        "flag_emoji": "🇳🇱",
        "description": "The Netherlands is one of the most popular study destinations in Europe with over 2,100 English-taught programs. Dutch universities are known for their innovative teaching methods, strong research output, and excellent career services. Amsterdam is a vibrant, multicultural city with a thriving startup scene.",
        "living_cost_monthly_display": "EUR 900 - 1,400/month",
        "living_cost_monthly_usd": 1100.0,
        "avg_rent_display": "EUR 500 - 900/month",
        "avg_food_display": "EUR 200 - 350/month",
        "avg_transport_display": "EUR 80 - 120/month",
        "student_visa_name": "MVV (Provisional Residence Permit)",
        "visa_processing_time": "4–8 weeks",
        "visa_fee_display": "EUR 192",
        "visa_requirements_summary": ["Admission letter", "Financial proof (EUR 900+/month)", "Health insurance", "Passport", "Accommodation proof"],
        "visa_difficulty": "Medium",
        "work_rights_during_study": "16 hours/week or full-time in June/July/August",
        "work_hours_per_week": 16,
        "post_study_work_visa": "Orientation Year Visa (Zoekjaar)",
        "post_study_work_duration": "1 year",
        "average_salary_display": "EUR 35,000 - 60,000/year",
        "top_industries": ["Technology", "Agriculture", "Finance", "Water Management", "Logistics"],
        "popular_courses": ["Business", "Data Science", "Engineering", "Agriculture", "International Relations"],
        "climate": "Temperate maritime; mild summers, cool winters, rainy and windy.",
        "official_language": "Dutch (English widely spoken)",
        "currency": "Euro (EUR)",
        "government_scholarships": [
            {"name": "Holland Scholarship", "amount": "EUR 5,000", "description": "For non-EU students pursuing a Bachelor's or Master's in the Netherlands"},
            {"name": "Orange Knowledge Programme", "amount": "Full scholarship", "description": "For students from select developing countries"},
        ],
        "ai_summary": "The Netherlands is ideal for students seeking English-taught programs in Europe at a fraction of UK tuition costs. The 1-year orientation visa provides opportunity to find work post-graduation, and the country's strong startup ecosystem is particularly appealing for entrepreneurship-oriented students.",
        "total_universities": 14,
        "is_featured": False
    },
    {
        "slug": "france",
        "name": "France",
        "flag_emoji": "🇫🇷",
        "description": "France is home to world-class grandes écoles and prestigious research institutions. Public universities in France charge very low tuition fees for all international students. Paris ranks among the best student cities globally, offering incredible cultural experiences alongside academic excellence.",
        "living_cost_monthly_display": "EUR 900 - 1,500/month",
        "living_cost_monthly_usd": 1150.0,
        "avg_rent_display": "EUR 500 - 900/month",
        "avg_food_display": "EUR 200 - 350/month",
        "avg_transport_display": "EUR 75 - 120/month",
        "student_visa_name": "Long Stay Student Visa (VLS-TS)",
        "visa_processing_time": "3–8 weeks",
        "visa_fee_display": "EUR 99",
        "visa_requirements_summary": ["Campus France registration", "Admission letter", "Financial proof", "Health insurance", "Accommodation proof"],
        "visa_difficulty": "Medium",
        "work_rights_during_study": "964 hours per year (~20 hours/week)",
        "work_hours_per_week": 20,
        "post_study_work_visa": "Talent Passport - Graduate",
        "post_study_work_duration": "1–4 years",
        "average_salary_display": "EUR 28,000 - 55,000/year",
        "top_industries": ["Fashion & Luxury", "Aerospace", "Finance", "Tourism", "Technology"],
        "popular_courses": ["Business", "Fashion Design", "Engineering", "Arts", "Hospitality"],
        "climate": "Continental in the east, oceanic in the west, Mediterranean in the south.",
        "official_language": "French (many programs in English)",
        "currency": "Euro (EUR)",
        "government_scholarships": [
            {"name": "Eiffel Excellence Scholarship", "amount": "EUR 1,181 - 1,400/month", "description": "For international Master's and PhD students"},
            {"name": "French Government Scholarship", "amount": "EUR 700/month", "description": "For students in French language programs"},
        ],
        "ai_summary": "France offers an exceptional balance of prestige and affordability. Public university tuition is under EUR 500/year even for international students. The Grandes Écoles (HEC Paris, Sciences Po, CentraleSupélec) are globally recognized across business and engineering fields.",
        "total_universities": 70,
        "is_featured": False
    }
]

# ============================================================
# UNIVERSITIES SEED DATA
# ============================================================
UNIVERSITIES_SEED = [
    # --- CANADA ---
    {
        "slug": "university-of-toronto",
        "name": "University of Toronto",
        "short_name": "U of T",
        "country": "Canada",
        "city": "Toronto",
        "university_type": "Public",
        "founded_year": 1827,
        "student_population": 97000,
        "website": "https://www.utoronto.ca",
        "description": "The University of Toronto is Canada's top university and consistently ranks among the global top 25. Known for groundbreaking research in AI, medicine, and engineering, U of T has produced Nobel laureates, heads of state, and transformative entrepreneurs.",
        "highlights": ["#1 in Canada", "AI Research Hub", "Top 25 Globally", "Largest Research Budget in Canada", "200+ Research Institutes"],
        "qs_ranking": 25,
        "the_ranking": 18,
        "us_news_ranking": 22,
        "acceptance_rate": 43.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 100,
        "pte_requirement": 60,
        "min_gpa": 3.0,
        "tuition_min": 30000,
        "tuition_max": 55000,
        "tuition_currency": "CAD",
        "tuition_display": "CAD 30,000 - 55,000/year",
        "living_cost_annual": 18000,
        "living_cost_display": "CAD 18,000 - 24,000/year",
        "application_fee": 180.0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "UofT International Scholar Award", "amount": "CAD 10,000", "type": "Merit"},
            {"name": "Pearson International Scholarship", "amount": "Full tuition + living", "type": "Full scholarship"},
            {"name": "Lester B. Pearson International", "amount": "CAD 50,000+", "type": "Full merit"}
        ],
        "employment_rate": 92.0,
        "average_salary_post_study": "CAD 65,000 - 110,000/year",
        "top_employers": ["Google", "Amazon", "RBC", "TD Bank", "McKinsey", "Microsoft"],
        "visa_difficulty": "Easy",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "CAD 12,000 - 18,000/year",
        "popular_courses": ["Computer Science", "Engineering", "Business", "Medicine", "Data Science", "Law"],
        "intake_months": ["September", "January"],
        "total_programs": 700,
        "latitude": 43.6629,
        "longitude": -79.3957,
        "address": "27 King's College Circle, Toronto, ON M5S 1A1, Canada",
        "is_featured": True
    },
    {
        "slug": "university-of-british-columbia",
        "name": "University of British Columbia",
        "short_name": "UBC",
        "country": "Canada",
        "city": "Vancouver",
        "university_type": "Public",
        "founded_year": 1908,
        "student_population": 66000,
        "website": "https://www.ubc.ca",
        "description": "UBC is one of Canada's most internationally recognized universities, consistently ranked among the world's top 40. Located in one of the world's most livable cities, Vancouver, UBC excels in forestry, mining, medicine, and technology research.",
        "highlights": ["Top 40 Globally", "Stunning Vancouver Campus", "Strong Research Output", "High International Student Population"],
        "qs_ranking": 38,
        "the_ranking": 40,
        "acceptance_rate": 52.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 90,
        "pte_requirement": 65,
        "min_gpa": 3.0,
        "tuition_min": 28000,
        "tuition_max": 50000,
        "tuition_currency": "CAD",
        "tuition_display": "CAD 28,000 - 50,000/year",
        "living_cost_annual": 20000,
        "living_cost_display": "CAD 20,000 - 26,000/year",
        "application_fee": 168.0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "UBC International Scholars Program", "amount": "CAD 10,000 - 40,000", "type": "Merit"},
            {"name": "Donald A. Wehrung International Student Award", "amount": "CAD 40,000+", "type": "Need-based"}
        ],
        "employment_rate": 90.0,
        "average_salary_post_study": "CAD 60,000 - 105,000/year",
        "top_employers": ["Amazon", "Microsoft", "Hootsuite", "Slack", "Apple"],
        "visa_difficulty": "Easy",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "CAD 14,000 - 20,000/year",
        "popular_courses": ["Computer Science", "Business", "Forestry", "Medicine", "Engineering"],
        "intake_months": ["September", "January"],
        "total_programs": 550,
        "latitude": 49.2606,
        "longitude": -123.2460,
        "address": "2329 West Mall, Vancouver, BC V6T 1Z4, Canada",
        "is_featured": True
    },
    {
        "slug": "mcgill-university",
        "name": "McGill University",
        "short_name": "McGill",
        "country": "Canada",
        "city": "Montreal",
        "university_type": "Public",
        "founded_year": 1821,
        "student_population": 40000,
        "website": "https://www.mcgill.ca",
        "description": "Founded in 1821, McGill is consistently ranked as Canada's most international university. Located in vibrant Montreal, McGill is globally recognized for medicine, law, and research excellence. Over 30% of its students are international.",
        "highlights": ["Canada's Most International University", "Strong Medical School", "Bilingual City (English & French)", "Extensive Research Funding"],
        "qs_ranking": 30,
        "the_ranking": 42,
        "acceptance_rate": 46.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 90,
        "min_gpa": 3.0,
        "tuition_min": 22000,
        "tuition_max": 45000,
        "tuition_currency": "CAD",
        "tuition_display": "CAD 22,000 - 45,000/year",
        "living_cost_annual": 16000,
        "living_cost_display": "CAD 16,000 - 22,000/year",
        "application_fee": 120.0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "McGill Entrance Scholarship", "amount": "CAD 3,000 - 12,000", "type": "Merit"},
            {"name": "McGill Principal's Graduate Fellowships", "amount": "CAD 15,000+", "type": "Research"}
        ],
        "employment_rate": 88.0,
        "average_salary_post_study": "CAD 55,000 - 100,000/year",
        "top_employers": ["Deloitte", "National Bank", "IBM", "Bombardier", "SNC-Lavalin"],
        "visa_difficulty": "Easy",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "CAD 10,000 - 16,000/year",
        "popular_courses": ["Medicine", "Law", "Engineering", "Business", "Life Sciences"],
        "intake_months": ["September", "January"],
        "total_programs": 300,
        "latitude": 45.5048,
        "longitude": -73.5772,
        "address": "845 Sherbrooke St W, Montreal, Quebec H3A 0G4, Canada",
        "is_featured": True
    },
    # --- UK ---
    {
        "slug": "imperial-college-london",
        "name": "Imperial College London",
        "short_name": "Imperial",
        "country": "United Kingdom",
        "city": "London",
        "university_type": "Public",
        "founded_year": 1907,
        "student_population": 20000,
        "website": "https://www.imperial.ac.uk",
        "description": "Imperial College London is a world-leading STEM university, consistently ranked in the global top 10. With a laser focus on science, engineering, medicine, and business, Imperial produces highly sought-after graduates who go on to lead global companies and research institutions.",
        "highlights": ["Top 10 Globally", "STEM Specialist", "London Location", "97% Graduate Employment", "Strong Industry Partnerships"],
        "qs_ranking": 8,
        "the_ranking": 11,
        "acceptance_rate": 14.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 92,
        "pte_requirement": 59,
        "min_gpa": 3.5,
        "tuition_min": 35000,
        "tuition_max": 50000,
        "tuition_currency": "GBP",
        "tuition_display": "GBP 35,000 - 50,000/year",
        "living_cost_annual": 18000,
        "living_cost_display": "GBP 18,000 - 25,000/year",
        "application_fee": 75.0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "President's PhD Scholarship", "amount": "GBP 20,000 + fees", "type": "Research"},
            {"name": "Imperial College India Scholarship", "amount": "GBP 10,000", "type": "Country-specific"}
        ],
        "employment_rate": 97.0,
        "average_salary_post_study": "GBP 45,000 - 85,000/year",
        "top_employers": ["BP", "Shell", "Goldman Sachs", "McKinsey", "Rolls-Royce", "AstraZeneca"],
        "visa_difficulty": "Medium",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "GBP 12,000 - 18,000/year",
        "popular_courses": ["Engineering", "Computing", "Medicine", "Business", "Data Science"],
        "intake_months": ["October"],
        "total_programs": 320,
        "latitude": 51.4988,
        "longitude": -0.1749,
        "address": "Exhibition Rd, South Kensington, London SW7 2AZ, UK",
        "is_featured": True
    },
    {
        "slug": "university-college-london",
        "name": "University College London",
        "short_name": "UCL",
        "country": "United Kingdom",
        "city": "London",
        "university_type": "Public",
        "founded_year": 1826,
        "student_population": 42000,
        "website": "https://www.ucl.ac.uk",
        "description": "UCL is London's leading multidisciplinary university and one of the world's top research institutions. Founded on principles of inclusivity, UCL was one of the first universities to admit women and students regardless of religion. Today it is a global powerhouse across science, arts, law, and engineering.",
        "highlights": ["Top 10 Globally", "Highly Diverse Campus", "London Location", "World-leading Research", "Nobel Prize Legacy"],
        "qs_ranking": 9,
        "the_ranking": 22,
        "acceptance_rate": 63.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 96,
        "min_gpa": 3.3,
        "tuition_min": 28000,
        "tuition_max": 45000,
        "tuition_currency": "GBP",
        "tuition_display": "GBP 28,000 - 45,000/year",
        "living_cost_annual": 17000,
        "living_cost_display": "GBP 17,000 - 24,000/year",
        "application_fee": 0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "UCL Global Engagement Scholarship", "amount": "GBP 7,500", "type": "Merit"},
            {"name": "Denys Holland Scholarship", "amount": "GBP 9,000/year", "type": "Need-based"}
        ],
        "employment_rate": 94.0,
        "average_salary_post_study": "GBP 38,000 - 75,000/year",
        "top_employers": ["Google", "Amazon", "KPMG", "PwC", "NHS", "BBC"],
        "visa_difficulty": "Medium",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "GBP 10,000 - 16,000/year",
        "popular_courses": ["Computer Science", "Laws", "Architecture", "Medicine", "Economics"],
        "intake_months": ["September"],
        "total_programs": 700,
        "latitude": 51.5246,
        "longitude": -0.1340,
        "address": "Gower St, London WC1E 6BT, UK",
        "is_featured": True
    },
    {
        "slug": "university-of-edinburgh",
        "name": "University of Edinburgh",
        "short_name": "Edinburgh",
        "country": "United Kingdom",
        "city": "Edinburgh",
        "university_type": "Public",
        "founded_year": 1583,
        "student_population": 43000,
        "website": "https://www.ed.ac.uk",
        "description": "One of Scotland's oldest and most prestigious universities, Edinburgh is a global leader in informatics, medicine, and arts. The vibrant Scottish capital provides an unmatched cultural backdrop, and Edinburgh's AI research is world-renowned.",
        "highlights": ["Top 20 Globally", "World-class AI Research", "Historic Scottish Capital", "Strong Alumni Network"],
        "qs_ranking": 22,
        "the_ranking": 30,
        "acceptance_rate": 44.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 92,
        "min_gpa": 3.0,
        "tuition_min": 26000,
        "tuition_max": 40000,
        "tuition_currency": "GBP",
        "tuition_display": "GBP 26,000 - 40,000/year",
        "living_cost_annual": 13000,
        "living_cost_display": "GBP 13,000 - 18,000/year",
        "application_fee": 0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "Edinburgh Global Online Learning Scholarship", "amount": "GBP 5,000", "type": "Merit"},
            {"name": "Principal's Career Development PhD Scholarship", "amount": "Full fees + stipend", "type": "Research"}
        ],
        "employment_rate": 91.0,
        "average_salary_post_study": "GBP 30,000 - 60,000/year",
        "top_employers": ["Skyscanner", "Baillie Gifford", "NHS Scotland", "IBM", "Amazon"],
        "visa_difficulty": "Medium",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "GBP 8,000 - 14,000/year",
        "popular_courses": ["Informatics", "Medicine", "Law", "Business", "Arts & Humanities"],
        "intake_months": ["September"],
        "total_programs": 500,
        "latitude": 55.9445,
        "longitude": -3.1892,
        "address": "Old College, South Bridge, Edinburgh EH8 9YL, UK",
        "is_featured": False
    },
    # --- AUSTRALIA ---
    {
        "slug": "university-of-melbourne",
        "name": "University of Melbourne",
        "short_name": "UniMelb",
        "country": "Australia",
        "city": "Melbourne",
        "university_type": "Public",
        "founded_year": 1853,
        "student_population": 52000,
        "website": "https://www.unimelb.edu.au",
        "description": "Australia's #1 university, the University of Melbourne is one of the world's great research-intensive universities. A member of the Group of Eight, Melbourne offers exceptional programs in law, medicine, engineering, and business through its distinctive Melbourne Model curriculum.",
        "highlights": ["Australia's #1 University", "Group of Eight Member", "World-class Research", "Top Graduate Outcomes"],
        "qs_ranking": 33,
        "the_ranking": 38,
        "acceptance_rate": 70.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 79,
        "pte_requirement": 58,
        "min_gpa": 2.8,
        "tuition_min": 40000,
        "tuition_max": 65000,
        "tuition_currency": "AUD",
        "tuition_display": "AUD 40,000 - 65,000/year",
        "living_cost_annual": 24000,
        "living_cost_display": "AUD 24,000 - 30,000/year",
        "application_fee": 100.0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "Melbourne International Undergraduate Scholarship", "amount": "AUD 10,000 - 23,000", "type": "Merit"},
            {"name": "Graduate Research Scholarships", "amount": "Full tuition + stipend", "type": "Research"}
        ],
        "employment_rate": 90.0,
        "average_salary_post_study": "AUD 65,000 - 100,000/year",
        "top_employers": ["Deloitte", "PwC", "ANZ", "Commonwealth Bank", "Google"],
        "visa_difficulty": "Easy",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "AUD 14,000 - 22,000/year",
        "popular_courses": ["Medicine", "Law", "Engineering", "Business", "Arts"],
        "intake_months": ["February", "July"],
        "total_programs": 450,
        "latitude": -37.7963,
        "longitude": 144.9614,
        "address": "Grattan St, Parkville VIC 3010, Australia",
        "is_featured": True
    },
    {
        "slug": "university-of-sydney",
        "name": "University of Sydney",
        "short_name": "USYD",
        "country": "Australia",
        "city": "Sydney",
        "university_type": "Public",
        "founded_year": 1850,
        "student_population": 73000,
        "website": "https://www.sydney.edu.au",
        "description": "Australia's oldest university and consistently ranked in the global top 50, the University of Sydney offers over 400 courses across 8 academic faculties. Its iconic sandstone campus in the heart of Sydney is one of Australia's most recognizable landmarks.",
        "highlights": ["Australia's Oldest University", "Iconic Sandstone Campus", "Largest International Student Community", "Strong Global Alumni Network"],
        "qs_ranking": 41,
        "the_ranking": 67,
        "acceptance_rate": 73.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 85,
        "pte_requirement": 58,
        "min_gpa": 2.8,
        "tuition_min": 38000,
        "tuition_max": 62000,
        "tuition_currency": "AUD",
        "tuition_display": "AUD 38,000 - 62,000/year",
        "living_cost_annual": 25000,
        "living_cost_display": "AUD 25,000 - 32,000/year",
        "application_fee": 0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "Sydney Scholars India Scholarship", "amount": "AUD 6,000 - 10,000", "type": "Country-specific"},
            {"name": "International Research Training Program Scholarship", "amount": "Full tuition + stipend", "type": "Research"}
        ],
        "employment_rate": 89.0,
        "average_salary_post_study": "AUD 62,000 - 95,000/year",
        "top_employers": ["Macquarie Group", "Atlassian", "PwC", "Google", "Westpac"],
        "visa_difficulty": "Easy",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "AUD 16,000 - 24,000/year",
        "popular_courses": ["Business", "Engineering", "Medicine", "Law", "Computer Science"],
        "intake_months": ["February", "July"],
        "total_programs": 400,
        "latitude": -33.8882,
        "longitude": 151.1876,
        "address": "Camperdown NSW 2006, Australia",
        "is_featured": True
    },
    {
        "slug": "australian-national-university",
        "name": "Australian National University",
        "short_name": "ANU",
        "country": "Australia",
        "city": "Canberra",
        "university_type": "Public",
        "founded_year": 1946,
        "student_population": 25000,
        "website": "https://www.anu.edu.au",
        "description": "ANU is Australia's national university and consistently ranks as the country's top university for research. Established by an Act of the Australian Parliament, ANU is uniquely positioned at the centre of Australia's public policy, international affairs, and scientific research.",
        "highlights": ["Australia's National University", "Top Research Funding", "Government & Policy Focus", "Beautiful Bush Capital Setting"],
        "qs_ranking": 34,
        "the_ranking": 62,
        "acceptance_rate": 35.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 80,
        "min_gpa": 3.0,
        "tuition_min": 36000,
        "tuition_max": 55000,
        "tuition_currency": "AUD",
        "tuition_display": "AUD 36,000 - 55,000/year",
        "living_cost_annual": 20000,
        "living_cost_display": "AUD 20,000 - 26,000/year",
        "application_fee": 0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "ANU Chancellor's International Scholarship", "amount": "25% tuition waiver", "type": "Merit"},
            {"name": "ANU PhD Scholarship", "amount": "Full tuition + AUD 29,000/year stipend", "type": "Research"}
        ],
        "employment_rate": 87.0,
        "average_salary_post_study": "AUD 58,000 - 90,000/year",
        "top_employers": ["Australian Government", "Department of Foreign Affairs", "CSIRO", "Australian Defence"],
        "visa_difficulty": "Easy",
        "campus_type": "Suburban",
        "accommodation_available": True,
        "accommodation_cost_display": "AUD 12,000 - 18,000/year",
        "popular_courses": ["Politics & International Relations", "Science", "Engineering", "Arts", "Law"],
        "intake_months": ["February", "July"],
        "total_programs": 300,
        "latitude": -35.2778,
        "longitude": 149.1185,
        "address": "Acton ACT 2601, Australia",
        "is_featured": False
    },
    # --- USA ---
    {
        "slug": "massachusetts-institute-of-technology",
        "name": "Massachusetts Institute of Technology",
        "short_name": "MIT",
        "country": "United States",
        "city": "Cambridge",
        "university_type": "Private",
        "founded_year": 1861,
        "student_population": 11500,
        "website": "https://www.mit.edu",
        "description": "MIT is the world's leading STEM institution and consistently ranks #1 in engineering and technology globally. Its culture of innovation has spawned some of the world's most transformative companies including Dropbox, Akamai, and iRobot. MIT graduates have founded companies worth over $2 trillion.",
        "highlights": ["#1 Engineering Globally", "Innovation Culture", "Startup Ecosystem", "80+ Nobel Laureates", "$3B+ Research Budget"],
        "qs_ranking": 1,
        "the_ranking": 5,
        "acceptance_rate": 4.0,
        "ielts_requirement": 7.0,
        "toefl_requirement": 90,
        "gre_requirement": 160,
        "min_gpa": 3.7,
        "tuition_min": 57000,
        "tuition_max": 65000,
        "tuition_currency": "USD",
        "tuition_display": "USD 57,000 - 65,000/year",
        "living_cost_annual": 25000,
        "living_cost_display": "USD 25,000 - 35,000/year",
        "application_fee": 75.0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "MIT Need-Based Financial Aid", "amount": "Up to full cost", "type": "Need-based"},
        ],
        "employment_rate": 98.0,
        "average_salary_post_study": "USD 95,000 - 180,000/year",
        "top_employers": ["Google", "Microsoft", "Goldman Sachs", "Apple", "McKinsey", "SpaceX"],
        "visa_difficulty": "Hard",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "USD 12,000 - 18,000/year",
        "popular_courses": ["Computer Science", "Electrical Engineering", "Physics", "Mathematics", "Artificial Intelligence"],
        "intake_months": ["September"],
        "total_programs": 60,
        "latitude": 42.3601,
        "longitude": -71.0942,
        "address": "77 Massachusetts Ave, Cambridge, MA 02139, USA",
        "is_featured": True
    },
    {
        "slug": "stanford-university",
        "name": "Stanford University",
        "short_name": "Stanford",
        "country": "United States",
        "city": "Stanford",
        "university_type": "Private",
        "founded_year": 1885,
        "student_population": 17000,
        "website": "https://www.stanford.edu",
        "description": "Stanford University is at the heart of Silicon Valley and is one of the world's most powerful universities for technology, entrepreneurship, and leadership. Stanford alumni have founded companies like Google, Netflix, Instagram, and LinkedIn, collectively worth over $5 trillion.",
        "highlights": ["Silicon Valley Location", "Top 5 Globally", "Startup Capital of the World", "Strong VC Network", "60,000+ Patents"],
        "qs_ranking": 5,
        "the_ranking": 3,
        "acceptance_rate": 4.0,
        "ielts_requirement": 7.0,
        "toefl_requirement": 100,
        "gre_requirement": 162,
        "min_gpa": 3.7,
        "tuition_min": 58000,
        "tuition_max": 65000,
        "tuition_currency": "USD",
        "tuition_display": "USD 58,000 - 65,000/year",
        "living_cost_annual": 28000,
        "living_cost_display": "USD 28,000 - 38,000/year",
        "application_fee": 90.0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "Stanford Need-Based Financial Aid", "amount": "Up to USD 60,000+", "type": "Need-based"},
            {"name": "Knight-Hennessy Scholars", "amount": "Full scholarship + USD 75,000/year stipend", "type": "Full merit"}
        ],
        "employment_rate": 98.0,
        "average_salary_post_study": "USD 100,000 - 200,000/year",
        "top_employers": ["Google", "Apple", "Facebook", "LinkedIn", "Palantir", "OpenAI"],
        "visa_difficulty": "Hard",
        "campus_type": "Suburban",
        "accommodation_available": True,
        "accommodation_cost_display": "USD 15,000 - 22,000/year",
        "popular_courses": ["Computer Science", "AI & Machine Learning", "Business (MBA)", "Law", "Bioengineering"],
        "intake_months": ["September"],
        "total_programs": 200,
        "latitude": 37.4275,
        "longitude": -122.1697,
        "address": "450 Serra Mall, Stanford, CA 94305, USA",
        "is_featured": True
    },
    {
        "slug": "university-of-southern-california",
        "name": "University of Southern California",
        "short_name": "USC",
        "country": "United States",
        "city": "Los Angeles",
        "university_type": "Private",
        "founded_year": 1880,
        "student_population": 48000,
        "website": "https://www.usc.edu",
        "description": "USC is consistently ranked among the top 25 universities in the USA, attracting the largest international student body of any US university. Located in the entertainment capital of the world, USC excels in engineering, business, film, and communications.",
        "highlights": ["Largest International Student Body in USA", "Trojan Network", "Entertainment Industry Hub", "Strong Engineering School"],
        "qs_ranking": 113,
        "the_ranking": 78,
        "acceptance_rate": 12.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 90,
        "gre_requirement": 315,
        "min_gpa": 3.5,
        "tuition_min": 63000,
        "tuition_max": 72000,
        "tuition_currency": "USD",
        "tuition_display": "USD 63,000 - 72,000/year",
        "living_cost_annual": 22000,
        "living_cost_display": "USD 22,000 - 30,000/year",
        "application_fee": 90.0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "Trustee Scholarship", "amount": "Full tuition", "type": "Merit"},
            {"name": "International Student Merit Award", "amount": "USD 10,000 - 30,000", "type": "Merit"}
        ],
        "employment_rate": 91.0,
        "average_salary_post_study": "USD 70,000 - 120,000/year",
        "top_employers": ["Warner Bros.", "Disney", "Apple", "Amazon", "Goldman Sachs", "Deloitte"],
        "visa_difficulty": "Hard",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "USD 14,000 - 20,000/year",
        "popular_courses": ["Computer Science", "Engineering", "Business", "Cinema Arts", "Communications"],
        "intake_months": ["August", "January"],
        "total_programs": 400,
        "latitude": 34.0195,
        "longitude": -118.2858,
        "address": "University Park, Los Angeles, CA 90089, USA",
        "is_featured": True
    },
    # --- GERMANY ---
    {
        "slug": "technical-university-of-munich",
        "name": "Technical University of Munich",
        "short_name": "TUM",
        "country": "Germany",
        "city": "Munich",
        "university_type": "Public",
        "founded_year": 1868,
        "student_population": 50000,
        "website": "https://www.tum.de",
        "description": "TUM is Germany's top technical university and consistently ranks in the global top 50. As a member of the prestigious TU9 network, TUM is a powerhouse in engineering, natural sciences, and technology. Research partnerships with BMW, Siemens, and MAN make it a gateway to Germany's industrial elite.",
        "highlights": ["Germany's Top Technical University", "Tuition-Free for Most Programs", "Strong Industry Links", "Munich Location", "EU Research Grants"],
        "qs_ranking": 37,
        "the_ranking": 48,
        "acceptance_rate": 30.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 88,
        "gre_requirement": 310,
        "min_gpa": 2.7,
        "tuition_min": 500,
        "tuition_max": 5000,
        "tuition_currency": "EUR",
        "tuition_display": "EUR 500 - 5,000/year (Semester fee only for most programs)",
        "living_cost_annual": 11000,
        "living_cost_display": "EUR 11,000 - 16,000/year",
        "application_fee": 0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "DAAD Scholarship", "amount": "EUR 750-1,200/month", "type": "External"},
            {"name": "TUM Foundation Fellowship", "amount": "EUR 600/month", "type": "Merit"},
            {"name": "Deutschlandstipendium", "amount": "EUR 300/month", "type": "Merit"}
        ],
        "employment_rate": 95.0,
        "average_salary_post_study": "EUR 50,000 - 80,000/year",
        "top_employers": ["BMW", "Siemens", "MAN", "Linde", "Allianz", "SAP"],
        "visa_difficulty": "Medium",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "EUR 350 - 700/month",
        "popular_courses": ["Mechanical Engineering", "Electrical Engineering", "Computer Science", "Informatics", "Business & Economics"],
        "intake_months": ["October", "April"],
        "total_programs": 160,
        "latitude": 48.1496,
        "longitude": 11.5674,
        "address": "Arcisstr. 21, 80333 Munich, Germany",
        "is_featured": True
    },
    {
        "slug": "rwth-aachen-university",
        "name": "RWTH Aachen University",
        "short_name": "RWTH Aachen",
        "country": "Germany",
        "city": "Aachen",
        "university_type": "Public",
        "founded_year": 1870,
        "student_population": 47000,
        "website": "https://www.rwth-aachen.de",
        "description": "RWTH Aachen is Germany's largest technical university and one of Europe's leading STEM institutions. Its close collaboration with industry partners makes it the preferred choice for engineering graduates entering the automotive, semiconductor, and manufacturing sectors.",
        "highlights": ["Germany's Largest Technical University", "Industry-focused Research", "Near Belgian & Dutch borders", "Engineering Excellence"],
        "qs_ranking": 106,
        "the_ranking": 144,
        "acceptance_rate": 60.0,
        "ielts_requirement": 6.0,
        "toefl_requirement": 80,
        "min_gpa": 2.5,
        "tuition_min": 250,
        "tuition_max": 2000,
        "tuition_currency": "EUR",
        "tuition_display": "EUR 250 - 2,000/year (Semester fee only)",
        "living_cost_annual": 9500,
        "living_cost_display": "EUR 9,500 - 13,000/year",
        "application_fee": 0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "DAAD Scholarship", "amount": "EUR 750-1,200/month", "type": "External"},
            {"name": "Deutschlandstipendium", "amount": "EUR 300/month", "type": "Merit"}
        ],
        "employment_rate": 93.0,
        "average_salary_post_study": "EUR 45,000 - 75,000/year",
        "top_employers": ["Ford Europe", "Philips", "BASF", "ThyssenKrupp", "Daimler"],
        "visa_difficulty": "Medium",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "EUR 300 - 600/month",
        "popular_courses": ["Mechanical Engineering", "Computer Science", "Electrical Engineering", "Chemical Engineering", "Materials Science"],
        "intake_months": ["October", "April"],
        "total_programs": 150,
        "latitude": 50.7793,
        "longitude": 6.0594,
        "address": "Templergraben 55, 52062 Aachen, Germany",
        "is_featured": False
    },
    # --- SINGAPORE ---
    {
        "slug": "national-university-of-singapore",
        "name": "National University of Singapore",
        "short_name": "NUS",
        "country": "Singapore",
        "city": "Singapore",
        "university_type": "Public",
        "founded_year": 1905,
        "student_population": 41000,
        "website": "https://www.nus.edu.sg",
        "description": "NUS is Asia's #1 university and consistently ranks in the global top 15. As Singapore's flagship research university, NUS excels in computing, engineering, law, and business. Its strategic location at the heart of Asia provides unparalleled access to Asia-Pacific markets and job opportunities.",
        "highlights": ["Asia's #1 University", "Global Top 15", "Strategic Asia Location", "World-class Research", "Strong Industry Partnerships"],
        "qs_ranking": 8,
        "the_ranking": 25,
        "acceptance_rate": 25.0,
        "ielts_requirement": 6.0,
        "toefl_requirement": 85,
        "min_gpa": 3.2,
        "tuition_min": 17000,
        "tuition_max": 35000,
        "tuition_currency": "SGD",
        "tuition_display": "SGD 17,000 - 35,000/year",
        "living_cost_annual": 18000,
        "living_cost_display": "SGD 18,000 - 25,000/year",
        "application_fee": 20.0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "ASEAN Undergraduate Scholarship", "amount": "Full scholarship", "type": "Country-specific"},
            {"name": "NUS Research Scholarship", "amount": "Full tuition + SGD 2,000/month", "type": "Research"},
            {"name": "Science & Technology Undergraduate Scholarship", "amount": "Full scholarship", "type": "Merit"}
        ],
        "employment_rate": 96.0,
        "average_salary_post_study": "SGD 55,000 - 95,000/year",
        "top_employers": ["DBS Bank", "Google", "Grab", "Temasek", "Goldman Sachs"],
        "visa_difficulty": "Medium",
        "campus_type": "Suburban",
        "accommodation_available": True,
        "accommodation_cost_display": "SGD 3,000 - 7,200/year",
        "popular_courses": ["Computer Science", "Business", "Engineering", "Medicine", "Law"],
        "intake_months": ["August"],
        "total_programs": 200,
        "latitude": 1.2966,
        "longitude": 103.7764,
        "address": "21 Lower Kent Ridge Rd, Singapore 119077",
        "is_featured": True
    },
    # --- IRELAND ---
    {
        "slug": "trinity-college-dublin",
        "name": "Trinity College Dublin",
        "short_name": "TCD",
        "country": "Ireland",
        "city": "Dublin",
        "university_type": "Public",
        "founded_year": 1592,
        "student_population": 20000,
        "website": "https://www.tcd.ie",
        "description": "Trinity College Dublin is Ireland's oldest and most prestigious university, founded in 1592 by Queen Elizabeth I. Located in the heart of Dublin, Trinity is a leading research-intensive university with exceptional programs in law, medicine, engineering, and computing.",
        "highlights": ["Ireland's Most Prestigious University", "Founded in 1592", "Dublin City Centre Location", "Tech Hub Access"],
        "qs_ranking": 87,
        "the_ranking": 155,
        "acceptance_rate": 55.0,
        "ielts_requirement": 6.5,
        "toefl_requirement": 88,
        "min_gpa": 3.0,
        "tuition_min": 18000,
        "tuition_max": 35000,
        "tuition_currency": "EUR",
        "tuition_display": "EUR 18,000 - 35,000/year",
        "living_cost_annual": 14000,
        "living_cost_display": "EUR 14,000 - 20,000/year",
        "application_fee": 55.0,
        "scholarship_available": True,
        "scholarship_details": [
            {"name": "Trinity Global Excellence Scholarship", "amount": "EUR 3,000 - 10,000", "type": "Merit"},
            {"name": "TCD Foundation Scholarship", "amount": "Free accommodation + allowance", "type": "Merit"}
        ],
        "employment_rate": 90.0,
        "average_salary_post_study": "EUR 40,000 - 70,000/year",
        "top_employers": ["Google Dublin", "Facebook Ireland", "Accenture", "Deloitte", "Stripe"],
        "visa_difficulty": "Easy",
        "campus_type": "Urban",
        "accommodation_available": True,
        "accommodation_cost_display": "EUR 8,000 - 14,000/year",
        "popular_courses": ["Computer Science", "Business", "Law", "Medicine", "Engineering"],
        "intake_months": ["September"],
        "total_programs": 420,
        "latitude": 53.3439,
        "longitude": -6.2546,
        "address": "College Green, Dublin 2, D02 PN40, Ireland",
        "is_featured": True
    }
]

# ============================================================
# COURSES SEED DATA
# ============================================================
COURSES_SEED = [
    # University of Toronto courses
    {
        "slug": "uoft-msc-computer-science",
        "university_slug": "university-of-toronto",
        "university_name": "University of Toronto",
        "country": "Canada",
        "name": "MSc Computer Science",
        "degree": "Master's",
        "field": "Computer Science",
        "duration_years": 2.0,
        "duration_display": "2 Years",
        "credits": 120,
        "mode": "Full-time",
        "tuition_display": "CAD 13,340/year",
        "tuition_annual": 13340.0,
        "tuition_currency": "CAD",
        "ielts_requirement": 6.5,
        "toefl_requirement": 100,
        "min_gpa": 3.3,
        "gre_requirement": 310,
        "scholarship_available": True,
        "scholarship_amount": "CAD 10,000 - 40,000",
        "career_outcomes": ["Software Engineer", "Machine Learning Engineer", "Research Scientist", "Data Scientist", "AI Engineer"],
        "salary_estimate_display": "CAD 90,000 - 150,000/year",
        "employment_rate": 95.0,
        "intake_months": ["September"],
        "application_deadline": "December 1 (Fall intake)",
        "description": "The MSc in Computer Science at UofT is one of the most prestigious CS graduate programs in North America. With specializations in AI/ML, systems, theory, and HCI, students work alongside world-leading researchers in the Vector Institute.",
        "curriculum_highlights": ["Machine Learning", "Deep Learning", "Distributed Systems", "Human-Computer Interaction", "Research Thesis"],
        "is_featured": True
    },
    {
        "slug": "uoft-mba-rotman",
        "university_slug": "university-of-toronto",
        "university_name": "University of Toronto",
        "country": "Canada",
        "name": "Master of Business Administration (MBA)",
        "degree": "Master's",
        "field": "Business Administration",
        "duration_years": 2.0,
        "duration_display": "2 Years",
        "credits": 60,
        "mode": "Full-time",
        "tuition_display": "CAD 99,000 total",
        "tuition_annual": 49500.0,
        "tuition_currency": "CAD",
        "ielts_requirement": 7.0,
        "toefl_requirement": 100,
        "min_gpa": 3.0,
        "gmat_requirement": 650,
        "work_experience_years": 2,
        "scholarship_available": True,
        "scholarship_amount": "CAD 10,000 - 25,000",
        "career_outcomes": ["Management Consultant", "Investment Banker", "Product Manager", "Strategy Director", "Entrepreneur"],
        "salary_estimate_display": "CAD 85,000 - 140,000/year",
        "employment_rate": 92.0,
        "intake_months": ["September"],
        "application_deadline": "January 10 (Round 2)",
        "description": "Rotman School of Management's Full-Time MBA is Canada's premier business education program. With its integrative thinking approach and proximity to Bay Street finance, it's the top choice for aspiring business leaders.",
        "curriculum_highlights": ["Strategic Management", "Financial Accounting", "Marketing Management", "Corporate Finance", "Leadership Development"],
        "is_featured": True
    },
    # UBC courses
    {
        "slug": "ubc-meng-electrical-engineering",
        "university_slug": "university-of-british-columbia",
        "university_name": "University of British Columbia",
        "country": "Canada",
        "name": "MEng Electrical and Computer Engineering",
        "degree": "Master's",
        "field": "Electrical Engineering",
        "duration_years": 1.5,
        "duration_display": "16 Months",
        "mode": "Full-time",
        "tuition_display": "CAD 16,000/year",
        "tuition_annual": 16000.0,
        "tuition_currency": "CAD",
        "ielts_requirement": 6.5,
        "toefl_requirement": 90,
        "min_gpa": 3.0,
        "scholarship_available": True,
        "scholarship_amount": "CAD 5,000 - 20,000",
        "career_outcomes": ["Electrical Engineer", "Embedded Systems Engineer", "Signal Processing Engineer", "Firmware Engineer"],
        "salary_estimate_display": "CAD 75,000 - 120,000/year",
        "employment_rate": 91.0,
        "intake_months": ["September", "January"],
        "application_deadline": "March 31",
        "description": "UBC's MEng in ECE combines advanced coursework with industry projects in power systems, communications, VLSI design, and control systems.",
        "curriculum_highlights": ["Digital Signal Processing", "Control Systems", "VLSI Design", "Power Electronics"],
        "is_featured": False
    },
    # Imperial College
    {
        "slug": "imperial-msc-ai",
        "university_slug": "imperial-college-london",
        "university_name": "Imperial College London",
        "country": "United Kingdom",
        "name": "MSc Artificial Intelligence",
        "degree": "Master's",
        "field": "Artificial Intelligence",
        "duration_years": 1.0,
        "duration_display": "1 Year",
        "mode": "Full-time",
        "tuition_display": "GBP 35,100/year",
        "tuition_annual": 35100.0,
        "tuition_currency": "GBP",
        "ielts_requirement": 6.5,
        "toefl_requirement": 92,
        "min_gpa": 3.5,
        "scholarship_available": True,
        "scholarship_amount": "GBP 10,000",
        "career_outcomes": ["AI Research Scientist", "ML Engineer", "NLP Engineer", "Computer Vision Engineer", "AI Product Manager"],
        "salary_estimate_display": "GBP 55,000 - 95,000/year",
        "employment_rate": 96.0,
        "intake_months": ["October"],
        "application_deadline": "June 30",
        "description": "Imperial's MSc in AI is among the most rigorous and respected AI programs globally. Students develop deep expertise in machine learning, neural networks, and intelligent systems through theory and intensive practical labs.",
        "curriculum_highlights": ["Machine Learning", "Neural Networks", "Probabilistic Reasoning", "Robotics", "Individual Research Project"],
        "is_featured": True
    },
    {
        "slug": "imperial-msc-data-science",
        "university_slug": "imperial-college-london",
        "university_name": "Imperial College London",
        "country": "United Kingdom",
        "name": "MSc Data Science",
        "degree": "Master's",
        "field": "Data Science",
        "duration_years": 1.0,
        "duration_display": "1 Year",
        "mode": "Full-time",
        "tuition_display": "GBP 35,500/year",
        "tuition_annual": 35500.0,
        "tuition_currency": "GBP",
        "ielts_requirement": 6.5,
        "toefl_requirement": 92,
        "min_gpa": 3.3,
        "scholarship_available": True,
        "scholarship_amount": "GBP 10,000",
        "career_outcomes": ["Data Scientist", "Data Engineer", "Business Intelligence Analyst", "Quantitative Analyst"],
        "salary_estimate_display": "GBP 45,000 - 80,000/year",
        "employment_rate": 95.0,
        "intake_months": ["October"],
        "application_deadline": "June 30",
        "description": "This intensive 1-year program at Imperial equips students with advanced statistical, computational, and machine learning skills for careers in industry and academia.",
        "curriculum_highlights": ["Statistical Learning", "Deep Learning", "Natural Language Processing", "Big Data Technologies", "Research Project"],
        "is_featured": True
    },
    # UCL courses
    {
        "slug": "ucl-msc-computer-science",
        "university_slug": "university-college-london",
        "university_name": "University College London",
        "country": "United Kingdom",
        "name": "MSc Computer Science",
        "degree": "Master's",
        "field": "Computer Science",
        "duration_years": 1.0,
        "duration_display": "1 Year",
        "mode": "Full-time",
        "tuition_display": "GBP 32,900/year",
        "tuition_annual": 32900.0,
        "tuition_currency": "GBP",
        "ielts_requirement": 6.5,
        "toefl_requirement": 96,
        "min_gpa": 3.0,
        "scholarship_available": True,
        "scholarship_amount": "GBP 7,500",
        "career_outcomes": ["Software Engineer", "Systems Architect", "Tech Lead", "Research Scientist"],
        "salary_estimate_display": "GBP 40,000 - 75,000/year",
        "employment_rate": 94.0,
        "intake_months": ["September"],
        "application_deadline": "March 31",
        "description": "UCL's MSc in Computer Science provides a comprehensive foundation in core CS theory and cutting-edge applications. The central London campus provides exceptional industry networking opportunities.",
        "curriculum_highlights": ["Algorithms", "Machine Learning", "Software Engineering", "Distributed Computing"],
        "is_featured": False
    },
    # University of Melbourne
    {
        "slug": "unimelb-master-of-engineering",
        "university_slug": "university-of-melbourne",
        "university_name": "University of Melbourne",
        "country": "Australia",
        "name": "Master of Engineering (Software)",
        "degree": "Master's",
        "field": "Software Engineering",
        "duration_years": 2.0,
        "duration_display": "2 Years",
        "credits": 200,
        "mode": "Full-time",
        "tuition_display": "AUD 46,000/year",
        "tuition_annual": 46000.0,
        "tuition_currency": "AUD",
        "ielts_requirement": 6.5,
        "toefl_requirement": 79,
        "pte_requirement": 58,
        "min_gpa": 2.75,
        "scholarship_available": True,
        "scholarship_amount": "AUD 10,000 - 23,000",
        "career_outcomes": ["Software Engineer", "Cloud Architect", "DevOps Engineer", "Full Stack Developer"],
        "salary_estimate_display": "AUD 80,000 - 130,000/year",
        "employment_rate": 92.0,
        "intake_months": ["February", "July"],
        "application_deadline": "October 31 (February intake)",
        "description": "Melbourne's Master of Engineering (Software) is an industry-aligned professional degree preparing graduates for careers in software development, systems design, and technology leadership.",
        "curriculum_highlights": ["Software Design Patterns", "Cloud Computing", "Agile Development", "Cybersecurity", "Industry Project"],
        "is_featured": True
    },
    # MIT courses
    {
        "slug": "mit-meng-computer-science",
        "university_slug": "massachusetts-institute-of-technology",
        "university_name": "Massachusetts Institute of Technology",
        "country": "United States",
        "name": "MEng Computer Science and Engineering",
        "degree": "Master's",
        "field": "Computer Science",
        "duration_years": 1.0,
        "duration_display": "1 Year (for MIT undergrads) / 2 Years (external)",
        "mode": "Full-time",
        "tuition_display": "USD 57,986/year",
        "tuition_annual": 57986.0,
        "tuition_currency": "USD",
        "ielts_requirement": 7.0,
        "toefl_requirement": 90,
        "gre_requirement": 165,
        "min_gpa": 3.7,
        "scholarship_available": True,
        "scholarship_amount": "Research/Teaching Assistantship (covers tuition + stipend)",
        "career_outcomes": ["Principal Engineer", "Research Scientist", "Startup Founder", "AI Researcher", "CTO"],
        "salary_estimate_display": "USD 120,000 - 200,000/year",
        "employment_rate": 99.0,
        "intake_months": ["September"],
        "application_deadline": "December 15",
        "description": "MIT's MEng in EECS is one of the world's most prestigious CS graduate programs, combining advanced theory with hands-on research and access to MIT's legendary lab ecosystem.",
        "curriculum_highlights": ["Advanced Algorithms", "Deep Learning", "Distributed Systems", "Quantum Computing", "Thesis Research"],
        "is_featured": True
    },
    # Stanford courses
    {
        "slug": "stanford-ms-computer-science",
        "university_slug": "stanford-university",
        "university_name": "Stanford University",
        "country": "United States",
        "name": "MS Computer Science",
        "degree": "Master's",
        "field": "Computer Science",
        "duration_years": 2.0,
        "duration_display": "1.5 - 2 Years",
        "credits": 45,
        "mode": "Full-time",
        "tuition_display": "USD 58,000/year",
        "tuition_annual": 58000.0,
        "tuition_currency": "USD",
        "ielts_requirement": 7.0,
        "toefl_requirement": 100,
        "gre_requirement": 163,
        "min_gpa": 3.5,
        "scholarship_available": True,
        "scholarship_amount": "Research Assistantship available",
        "career_outcomes": ["Senior Engineer", "Research Scientist", "AI/ML Lead", "Tech Entrepreneur", "Product Manager"],
        "salary_estimate_display": "USD 130,000 - 220,000/year",
        "employment_rate": 98.0,
        "intake_months": ["September"],
        "application_deadline": "December 1",
        "description": "Stanford's MS in CS is one of the most sought-after graduate programs globally. With specializations in AI, systems, HCI, and theory, it sits at the epicenter of Silicon Valley innovation.",
        "curriculum_highlights": ["Machine Learning", "Systems Design", "Natural Language Processing", "Computer Vision", "AI Ethics"],
        "is_featured": True
    },
    # TUM courses
    {
        "slug": "tum-msc-informatics",
        "university_slug": "technical-university-of-munich",
        "university_name": "Technical University of Munich",
        "country": "Germany",
        "name": "MSc Informatics",
        "degree": "Master's",
        "field": "Computer Science",
        "duration_years": 2.0,
        "duration_display": "2 Years",
        "credits": 120,
        "mode": "Full-time",
        "tuition_display": "EUR 258 semester fee only (No tuition)",
        "tuition_annual": 516.0,
        "tuition_currency": "EUR",
        "ielts_requirement": 7.0,
        "toefl_requirement": 95,
        "min_gpa": 2.5,
        "scholarship_available": True,
        "scholarship_amount": "DAAD EUR 750-1,200/month",
        "career_outcomes": ["Software Engineer", "AI Researcher", "Systems Engineer", "Data Scientist", "Tech Lead"],
        "salary_estimate_display": "EUR 55,000 - 85,000/year",
        "employment_rate": 96.0,
        "intake_months": ["October", "April"],
        "application_deadline": "May 31 (Winter semester)",
        "description": "TUM's Informatics program is taught entirely in English and is one of the best computer science programs in Europe — at virtually zero tuition cost. Students specialize in AI, robotics, bioinformatics, or software engineering.",
        "curriculum_highlights": ["Advanced Algorithms", "Machine Learning", "Robotics", "Bioinformatics", "Software Quality"],
        "is_featured": True
    },
    # NUS courses
    {
        "slug": "nus-msc-computing",
        "university_slug": "national-university-of-singapore",
        "university_name": "National University of Singapore",
        "country": "Singapore",
        "name": "MSc Computing",
        "degree": "Master's",
        "field": "Computer Science",
        "duration_years": 1.0,
        "duration_display": "1 Year",
        "credits": 40,
        "mode": "Full-time",
        "tuition_display": "SGD 18,800 total",
        "tuition_annual": 18800.0,
        "tuition_currency": "SGD",
        "ielts_requirement": 6.0,
        "toefl_requirement": 85,
        "min_gpa": 3.2,
        "scholarship_available": True,
        "scholarship_amount": "SGD Research Scholarship (full tuition + stipend)",
        "career_outcomes": ["Software Engineer", "Data Scientist", "AI Engineer", "Systems Analyst"],
        "salary_estimate_display": "SGD 60,000 - 100,000/year",
        "employment_rate": 96.0,
        "intake_months": ["August"],
        "application_deadline": "February 28",
        "description": "NUS's MSc in Computing is a world-class 1-year program providing advanced training in algorithms, systems, and AI. Its location in Singapore provides access to Asia's booming tech sector.",
        "curriculum_highlights": ["Algorithm Design", "Machine Learning", "Cloud Computing", "Cybersecurity", "Research Dissertation"],
        "is_featured": True
    },
]


def seed_explorer_data(db: Session):
    """
    Seeds countries, universities, and courses into the Explorer database tables.
    Safe to call on every startup — idempotent (skips existing records).
    """
    from ..models import ExplorerUniversity, ExplorerCourse, ExplorerCountry

    try:
        # ---- Seed Countries ----
        country_count = db.query(ExplorerCountry).count()
        if country_count == 0:
            for c in COUNTRIES_SEED:
                db.add(ExplorerCountry(**c))
            db.commit()
            logger.info(f"Explorer: Seeded {len(COUNTRIES_SEED)} countries.")
        else:
            logger.info(f"Explorer: Countries already seeded ({country_count} records).")

        # ---- Seed Universities ----
        uni_count = db.query(ExplorerUniversity).count()
        if uni_count == 0:
            for u in UNIVERSITIES_SEED:
                db.add(ExplorerUniversity(**u))
            db.commit()
            logger.info(f"Explorer: Seeded {len(UNIVERSITIES_SEED)} universities.")
        else:
            logger.info(f"Explorer: Universities already seeded ({uni_count} records).")

        # ---- Seed Courses ----
        course_count = db.query(ExplorerCourse).count()
        if course_count == 0:
            for c in COURSES_SEED:
                university_slug = c.pop("university_slug")
                uni = db.query(ExplorerUniversity).filter(ExplorerUniversity.slug == university_slug).first()
                if uni:
                    db.add(ExplorerCourse(university_id=uni.id, **c))
            db.commit()
            logger.info(f"Explorer: Seeded {len(COURSES_SEED)} courses.")
        else:
            logger.info(f"Explorer: Courses already seeded ({course_count} records).")

    except Exception as e:
        logger.error(f"Explorer seed failed: {str(e)}")
        db.rollback()


def get_ai_university_summary(university_name: str, country: str, course: str, student_profile: dict) -> str:
    """
    Generates an AI-powered university summary for a specific student profile using OpenAI.
    """
    try:
        from ..config import settings
        from .openai_service import ReplicateOpenAIMock
        import openai

        if not settings.openai_api_key:
            return f"{university_name} is a world-class institution in {country} offering excellent opportunities for {course} students."

        if settings.openai_api_key.startswith("sk-"):
            client = openai.OpenAI(api_key=settings.openai_api_key)
        else:
            client = ReplicateOpenAIMock(api_key=settings.openai_api_key)

        gpa = student_profile.get("gpa", "N/A")
        ielts = student_profile.get("ielts", "N/A")
        budget = student_profile.get("budget", "N/A")
        target_degree = student_profile.get("degree", "Master's")

        prompt = f"""You are Aura AI, a study abroad expert. Provide a 3-sentence personalized analysis for this student considering {university_name} in {country} for {course} ({target_degree}).

Student Profile:
- GPA: {gpa}
- IELTS: {ielts}  
- Budget: {budget}

Cover: admission chances, scholarship potential, and career outcomes. Be specific and encouraging but realistic. Keep it under 120 words."""

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=200,
            temperature=0.7
        )
        return response.choices[0].message.content.strip()

    except Exception as e:
        logger.error(f"AI summary generation failed: {str(e)}")
        return f"{university_name} offers excellent {course} programs in {country}. Contact Aura AI for a personalized admission analysis."
